CREATE TABLE public.tb_usuarios (
	idusuario integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	login varchar(50) NOT NULL,
	nome varchar(1000) NOT NULL,
	senha varchar(5000) NOT NULL,
	datacriacao timestamp with time zone NOT NULL,
	CONSTRAINT tb_usuarios_pk PRIMARY KEY (idusuario)
);

CREATE TABLE public.tb_tipos_permissoes (
	idtipopermissao integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome varchar(100) NOT NULL,
	datacriacao timestamp with time zone NOT NULL,
	CONSTRAINT tb_tipos_permissoes_pk PRIMARY KEY (idtipopermissao)
);


CREATE TABLE public.tb_status_medicao (
	idstatusmedicao integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome varchar(100) NOT NULL,
	datacriacao timestamp with time zone NOT NULL,
	CONSTRAINT tb_status_medicao_pk PRIMARY KEY (idstatusmedicao)
);


CREATE TABLE public.tb_quantidade (
	idquantidade integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome varchar(10) NOT NULL,
	datacriacao timestamp with time zone NOT NULL
);

CREATE TABLE public.tb_origem (
	idorigem integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome varchar(50) NOT NULL,
	datacriacao timestamp with time zone NOT NULL
);

CREATE TABLE public.tb_grupos (
	idgrupo integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome varchar(50) NOT NULL,
	datacriacao timestamp with time zone NOT NULL
);

CREATE TABLE public.tb_projetos (
	idprojeto integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nomeprojeto varchar(500) NOT NULL,
	datacriacao timestamp with time zone NOT NULL,
	CONSTRAINT tb_projetos_pk PRIMARY KEY (idprojeto)
);

ALTER TABLE public.tb_quantidade ADD CONSTRAINT tb_quantidade_pk PRIMARY KEY (idquantidade);

ALTER TABLE public.tb_origem ADD CONSTRAINT tb_origem_unique UNIQUE (idorigem);

ALTER TABLE public.tb_grupos ADD CONSTRAINT tb_grupos_unique UNIQUE (idgrupo);

CREATE TABLE public.tb_item (
	iditem integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	identificador varchar(50) NOT NULL,
	codigo varchar(50) NOT NULL,
	idorigem integer NOT NULL,
	descricao varchar(1000) NOT NULL,
	unidade numeric(10, 2) NULL,
	idquantidade integer NULL,
	valorsembdi numeric(10, 2) NULL,
	valorcombdi numeric(10, 2) NULL,
	valortotalcombdi numeric(10, 2) NULL,
	iditempai integer NULL,
	datacriacao timestamp with time zone NOT NULL,
	ordem integer NOT NULL,
	CONSTRAINT tb_item_pk PRIMARY KEY (iditem),
	CONSTRAINT tb_item_tb_origem_fk FOREIGN KEY (idorigem) REFERENCES public.tb_origem(idorigem),
	CONSTRAINT tb_item_tb_quantidade_fk FOREIGN KEY (idquantidade) REFERENCES public.tb_quantidade(idquantidade),
	CONSTRAINT tb_item_tb_item_fk FOREIGN KEY (iditempai) REFERENCES public.tb_item(iditem)
);

CREATE TABLE IF NOT EXISTS public.tb_contratos
(
    idprojeto integer NOT NULL,
    datacontrato timestamp with time zone NOT NULL,
    numerocontrato character varying(50) COLLATE pg_catalog."default" NOT NULL,
    valortotalprevisto numeric(10,2),
    valortotalsolicitado numeric(10,2),
    valortotalmedido numeric(10,2),
    valorsaldorestante numeric(10,2),
    datacriacao timestamp with time zone NOT NULL,
    datadelecao timestamp with time zone,
    "empresaId" integer,
    valor numeric(10,2),
    tipocontratacao integer,
    gerente character varying(200) COLLATE pg_catalog."default",
    datatermino timestamp with time zone,
    datainicio timestamp with time zone,
    "prefeituraId" integer,
    "idcontrato" integer NOT NULL DEFAULT nextval('tb_contratos_idcontrato_seq'::regclass),
    CONSTRAINT tb_contratos_pkey PRIMARY KEY ("idContrato"),
    CONSTRAINT tb_contratos_tb_empresas_fk FOREIGN KEY ("empresaId")
        REFERENCES public.tb_empresa (empresaid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT tb_contratos_tb_projetos_fk FOREIGN KEY (idprojeto)
        REFERENCES public.tb_projetos (idprojeto) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tb_contratos
    OWNER to postgres;


CREATE TABLE public.tb_items_contrato (
	iditemcontrato integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	idcontrato integer NOT NULL,
	iditem integer NOT NULL,
	idquantidade integer NOT NULL,
	unidade numeric(10, 2) NOT NULL,
	valorsembdi numeric(10, 2) NOT NULL,
	valorcombdi numeric(10, 2) NOT NULL,
	valortotalcombdi numeric(10, 2) NOT NULL,
	datacriacao timestamp with time zone NOT NULL,
	CONSTRAINT tb_items_contrato_pk PRIMARY KEY (iditemcontrato),
	CONSTRAINT tb_items_contrato_tb_item_fk FOREIGN KEY (iditem) REFERENCES public.tb_item(iditem),
	CONSTRAINT tb_items_contrato_tb_contratos_fk FOREIGN KEY (idcontrato) REFERENCES public.tb_contratos(idcontrato),
	CONSTRAINT tb_items_contrato_tb_quantidade_fk FOREIGN KEY (idquantidade) REFERENCES public.tb_quantidade(idquantidade)
);


CREATE TABLE public.tb_medicoes_projeto (
	idmedicoesprojeto integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	numeromedicao integer NOT NULL,
	idcontrato integer NOT NULL,
	datamedicao timestamp with time zone NOT NULL,
	resumo varchar(5000) NULL,
	idstatusmedicao integer NOT NULL,
	CONSTRAINT tb_medicoes_projeto_pk PRIMARY KEY (idmedicoesprojeto),
	CONSTRAINT tb_medicoes_projeto_tb_contratos_fk FOREIGN KEY (idcontrato) REFERENCES public.tb_contratos(idcontrato),
	CONSTRAINT tb_medicoes_projeto_tb_status_medicao_fk FOREIGN KEY (idstatusmedicao) REFERENCES public.tb_status_medicao(idstatusmedicao)
);


CREATE TABLE public.tb_items_medicoes_projeto (
	iditemmedicoesprojeto integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	idmedicoesprojeto integer NOT NULL,
	iditemcontrato integer NOT NULL,
	unidade numeric(10, 2) NOT NULL,
	datacriacao timestamp with time zone NOT NULL,
	CONSTRAINT tb_items_medicoes_projeto_pk PRIMARY KEY (iditemmedicoesprojeto),
	CONSTRAINT tb_items_medicoes_projeto_tb_medicoes_projeto_fk FOREIGN KEY (idmedicoesprojeto) REFERENCES public.tb_medicoes_projeto(idmedicoesprojeto),
	CONSTRAINT tb_items_medicoes_projeto_tb_items_contrato_fk FOREIGN KEY (iditemcontrato) REFERENCES public.tb_items_contrato(iditemcontrato)
);


CREATE TABLE public.tb_log_status_medicao (
	idlogstatusmedicao integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	idusuario integer NOT NULL,
	datalog timestamp with time zone NOT NULL,
	idmedicoesprojeto integer NOT NULL,
	idstatusmedicao integer NOT NULL,
	motivostatusmedicao varchar(500) NULL,
	CONSTRAINT tb_log_status_medicao_pk PRIMARY KEY (idlogstatusmedicao),
	CONSTRAINT tb_log_status_medicao_tb_usuarios_fk FOREIGN KEY (idusuario) REFERENCES public.tb_usuarios(idusuario),
	CONSTRAINT tb_log_status_medicao_tb_medicoes_projeto_fk FOREIGN KEY (idmedicoesprojeto) REFERENCES public.tb_medicoes_projeto(idmedicoesprojeto),
	CONSTRAINT tb_log_status_medicao_tb_status_medicao_fk FOREIGN KEY (idstatusmedicao) REFERENCES public.tb_status_medicao(idstatusmedicao)
);


CREATE TABLE public.tb_permissoes (
	idpermissao integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	idtipopermissao integer NOT NULL,
	datacriacao timestamp with time zone NOT NULL,
	idgrupo integer NOT NULL,
	CONSTRAINT tb_permissoes_pk PRIMARY KEY (idpermissao),
	CONSTRAINT tb_permissoes_tb_tipos_permissoes_fk FOREIGN KEY (idtipopermissao) REFERENCES public.tb_tipos_permissoes(idtipopermissao),
	CONSTRAINT tb_permissoes_tb_grupos_fk FOREIGN KEY (idgrupo) REFERENCES public.tb_grupos(idgrupo)
);

ALTER TABLE public.tb_usuarios ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_tipos_permissoes ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_status_medicao ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_quantidade ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_origem ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_grupos ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_projetos ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_item ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_contratos ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_items_contrato ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_medicoes_projeto ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_items_medicoes_projeto ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_log_status_medicao ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_permissoes ADD datadelecao timestamp with time zone NULL;

ALTER TABLE public.tb_medicoes_projeto ADD datacriacao timestamp with time zone NOT NULL;

CREATE TABLE public.tb_usuarios_grupos (
	idusuariogrupo integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	idusuario integer NOT NULL,
	idgrupo integer NOT NULL,
	datacriacao timestamp with time zone NOT NULL,
	datadelecao timestamp with time zone NULL,
	CONSTRAINT tb_usuarios_grupos_pk PRIMARY KEY (idusuariogrupo),
	CONSTRAINT tb_usuarios_grupos_tb_grupos_fk FOREIGN KEY (idgrupo) REFERENCES public.tb_grupos(idgrupo),
	CONSTRAINT tb_usuarios_grupos_tb_usuarios_fk FOREIGN KEY (idusuario) REFERENCES public.tb_usuarios(idusuario)
);

ALTER TABLE public.tb_items_contrato RENAME COLUMN iditem TO "ItemIdItem";

ALTER TABLE public.tb_item RENAME COLUMN idorigem TO "OrigemIdOrigem";

ALTER TABLE public.tb_item RENAME COLUMN idquantidade TO "QuantidadeIdQuantidade";

ALTER TABLE public.tb_items_contrato RENAME COLUMN idquantidade TO "QuantidadeIdQuantidade";

ALTER TABLE public.tb_log_status_medicao ADD datacriacao timestamp with time zone NOT NULL;

CREATE TABLE IF NOT EXISTS public.tb_empresa
(
    "empresaId" integer AS IDENTITY NOT NULL,
    nome character varying(200) COLLATE pg_catalog."default" NOT NULL,
    datacriacao timestamp with time zone NOT NULL,
    datadelecao timestamp with time zone,
    logo character varying(5000) NOT NULL COLLATE pg_catalog."default",
    CONSTRAINT tb_empresa_pkey PRIMARY KEY ("empresaId")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tb_empresa
    OWNER to postgres;

ALTER TABLE tb_empresa
DROP CONSTRAINT IF EXISTS tb_empresa_pkey;

ALTER TABLE tb_empresa
DROP COLUMN empresaId;

ALTER TABLE tb_empresa
ADD COLUMN empresaId INTEGER;

CREATE SEQUENCE tb_empresa_idEmpresa_seq;

ALTER TABLE tb_empresa
ALTER COLUMN empresaId SET DEFAULT nextval('tb_empresa_idEmpresa_seq');

ALTER TABLE tb_prefeitura
ADD PRIMARY KEY (idPrefeitura);

CREATE TABLE IF NOT EXISTS public.tb_prefeitura
(
    "idPrefeitura" integer AS IDENTITY NOT NULL NOT NULL,
    nome character varying(200) COLLATE pg_catalog."default" NOT NULL,
    datacriacao timestamp with time zone NOT NULL,
    datadelecao timestamp with time zone,
    logo character varying(5000) NOT NULL COLLATE pg_catalog."default",
    CONSTRAINT tb_prefeitura_pkey PRIMARY KEY ("idPrefeitura")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tb_prefeitura
    OWNER to postgres;


ALTER TABLE tb_prefeitura
DROP CONSTRAINT IF EXISTS tb_prefeitura_pkey;  -- Substitua pelo nome correto da chave primária, se houver

ALTER TABLE tb_prefeitura
DROP COLUMN idPrefeitura;

ALTER TABLE tb_prefeitura
ADD COLUMN idPrefeitura INTEGER;

CREATE SEQUENCE tb_prefeitura_idPrefeitura_seq;

ALTER TABLE tb_prefeitura
ALTER COLUMN idPrefeitura SET DEFAULT nextval('tb_prefeitura_idPrefeitura_seq');

ALTER TABLE tb_prefeitura
ADD PRIMARY KEY (idPrefeitura);


CREATE TABLE IF NOT EXISTS public.tb_parametros_sistema
(
    emailfinanceiro character varying(500) COLLATE pg_catalog."default",
    id integer NOT NULL DEFAULT nextval('tb_parametros_sistema_id_sequence'::regclass),
    CONSTRAINT tb_parametros_sistema_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tb_parametros_sistema
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.tb_arquivos_medicoes_projeto
(
    id integer NOT NULL DEFAULT nextval('tb_arquivos_medicoes_projeto_id_sequence'::regclass),
    idmedicoesprojeto integer NOT NULL,
    datacriacao timestamp with time zone NOT NULL,
    arquivomedicao character varying(5000) COLLATE pg_catalog."default" NOT NULL,
    datadelecao timestamp with time zone,
    CONSTRAINT tb_arquivos_medicoes_projeto_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tb_arquivos_medicoes_projeto
    OWNER to postgres;