//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrefeituraCachoeiro.Compartilhado {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Aditivos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Aditivos() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrefeituraCachoeiro.Compartilhado.Aditivos", typeof(Aditivos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O aditivo foi deletado.
        /// </summary>
        public static string AditivoDeletado {
            get {
                return ResourceManager.GetString("AditivoDeletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O aditivo não pode ser importado porque ele extrapola o limite de 25% do valor total previsto {0} para o contrato.
        /// </summary>
        public static string AditivoExtrapolouLimite {
            get {
                return ResourceManager.GetString("AditivoExtrapolouLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O aditivo não pode ser excluído porque já tem medições de projeto associadas a ele.
        /// </summary>
        public static string AditivoNaoPodeSerExcluido {
            get {
                return ResourceManager.GetString("AditivoNaoPodeSerExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O arquivo foi apagado.
        /// </summary>
        public static string ArquivoAditivoApagado {
            get {
                return ResourceManager.GetString("ArquivoAditivoApagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de validade informada para o aditivo é inferior a data de término do contrato. A data de validade do aditivo deve ser superior a data de término do contrato..
        /// </summary>
        public static string DataValidadeAditivoInferiorADataTerminoContrato {
            get {
                return ResourceManager.GetString("DataValidadeAditivoInferiorADataTerminoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Identificador do aditivo informado não foi encontrado.
        /// </summary>
        public static string IdAditivoNaoEncontrado {
            get {
                return ResourceManager.GetString("IdAditivoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi encontrado nenhum arquivo de Aditivo com o Id informado.
        /// </summary>
        public static string IdArquivoAditivoNaoEncontrado {
            get {
                return ResourceManager.GetString("IdArquivoAditivoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi encontrado nenhum aditivo para o contrato informado.
        /// </summary>
        public static string NenhumAditivoEncontradoParaoContratoInformado {
            get {
                return ResourceManager.GetString("NenhumAditivoEncontradoParaoContratoInformado", resourceCulture);
            }
        }
    }
}
