//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrefeituraCachoeiro.Compartilhado {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MedicoesProjeto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MedicoesProjeto() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrefeituraCachoeiro.Compartilhado.MedicoesProjeto", typeof(MedicoesProjeto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O apontamento de uma medição requer que na lista de items tenha pelo menos um item.
        /// </summary>
        public static string ApontamentoMedicaoProjetoRequerPeloMenosUmItem {
            get {
                return ResourceManager.GetString("ApontamentoMedicaoProjetoRequerPeloMenosUmItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Só é possível alterar uma medição que esteja no status de criada..
        /// </summary>
        public static string MedicaoNaoPodeSerAlterada {
            get {
                return ResourceManager.GetString("MedicaoNaoPodeSerAlterada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Só é possível aprovar uma medição que esteja no status de criada.
        /// </summary>
        public static string MedicaoNaoPodeSerAprovada {
            get {
                return ResourceManager.GetString("MedicaoNaoPodeSerAprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Só é possível reprovar uma medição que esteja no status de criada.
        /// </summary>
        public static string MedicaoNaoPodeSerReprovada {
            get {
                return ResourceManager.GetString("MedicaoNaoPodeSerReprovada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi encontrado nenhuma medição de projeto com o identificador informado.
        /// </summary>
        public static string MedicoesProjetoIdNaoEncontrado {
            get {
                return ResourceManager.GetString("MedicoesProjetoIdNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi encontrada nenhuma medição de projeto com os parâmetros de pesquisa informados..
        /// </summary>
        public static string MedicoesProjetoNaoEncontrados {
            get {
                return ResourceManager.GetString("MedicoesProjetoNaoEncontrados", resourceCulture);
            }
        }
    }
}
